services:
  testrunner:
    build:
      context: .
      dockerfile: Dockerfile.Runner
    image: midge:test
    container_name: midge-testrunner
    volumes:
      - ./results:/output
    environment:
      RUST_BACKTRACE: 1
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1GB
        reservations:
          cpus: 2
          memory: 1GB
    entrypoint: /bin/bash
    command: -c "(cargo test && cargo bench --bench 'tier1_*' --bench 'tier2_*' && cargo stress --verbose --warmup 1) 2>&1 | tee /output/test-results.log"
