//! Property-based tests for parser components.
//!
//! These tests use `proptest` to generate random inputs and verify that parsers
//! handle all inputs gracefully without panicking. This provides similar coverage
//! to fuzz testing but works on stable Rust and all platforms.
//!
//! Run with: `cargo test --test proptest_parsers`

use bytes::Bytes;
use proptest::prelude::*;

use cntryl_midge::common::internal_key::{
    decode_internal_key, decode_internal_key_typed, encode_internal_key_typed, EntryType,
};
use cntryl_midge::common::tlv::{decode_varint32, decode_varint64, TlvReader};
use cntryl_midge::sst::{Block, BlockType, BloomFilter, SparseIndex};
use cntryl_midge::wal::{decode, encoding::decode_borrowed};

// ============================================================================
// TLV Parser Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_parsing_tlv(data in prop::collection::vec(any::<u8>(), 0..1024)) {
        // Arrange - data is generated by proptest

        // Act - parse should never panic
        let reader = TlvReader::new(&data);
        for _ in reader {
            // Just consume the iterator
        }

        // Assert - reaching here without panic is success
    }

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_varint32(data in prop::collection::vec(any::<u8>(), 0..16)) {
        // Arrange - data is generated by proptest

        // Act - decode should return Ok or Err, never panic
        let _ = decode_varint32(&data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_varint64(data in prop::collection::vec(any::<u8>(), 0..16)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = decode_varint64(&data);

        // Assert - implicit (no panic)
    }
}

// ============================================================================
// WAL Decoder Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_wal_record(data in prop::collection::vec(any::<u8>(), 0..1024)) {
        // Arrange - data is generated by proptest

        // Act - decode should return Ok or Err, never panic
        let _ = decode(&data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_wal_record_borrowed(data in prop::collection::vec(any::<u8>(), 0..1024)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = decode_borrowed(&data);

        // Assert - implicit (no panic)
    }
}

// ============================================================================
// SST Block Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(5_000))]

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_data_block(data in prop::collection::vec(any::<u8>(), 0..4096)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = Block::decode(&data, BlockType::Data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_index_block(data in prop::collection::vec(any::<u8>(), 0..4096)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = Block::decode(&data, BlockType::Index);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_sparse_index(data in prop::collection::vec(any::<u8>(), 0..4096)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = SparseIndex::decode(&data);

        // Assert - implicit (no panic)
    }
}

// ============================================================================
// Bloom Filter Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(5_000))]

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_bloom_filter(data in prop::collection::vec(any::<u8>(), 0..1024)) {
        // Arrange - data is generated by proptest

        // Act
        if let Ok(filter) = BloomFilter::decode_block(&data) {
            // If decoding succeeds, also test query
            let _ = filter.may_contain(&data);
            let _ = filter.may_contain(&[]);
        }

        // Assert - implicit (no panic)
    }
}

// ============================================================================
// Internal Key Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    #[test]
    fn should_not_panic_given_arbitrary_bytes_when_decoding_internal_key(data in prop::collection::vec(any::<u8>(), 0..256)) {
        // Arrange - data is generated by proptest

        // Act
        let _ = decode_internal_key(&data);
        let _ = decode_internal_key_typed(&data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_roundtrip_given_valid_internal_key_when_encoding_then_decoding(
        user_key in prop::collection::vec(any::<u8>(), 0..200),
        seq in any::<u64>(),
        entry_type in prop_oneof![
            Just(EntryType::Value),
            Just(EntryType::Tombstone),
            Just(EntryType::RangeTombstone),
        ]
    ) {
        // Arrange - user_key, seq, entry_type from proptest

        // Act
        let encoded = encode_internal_key_typed(&user_key, seq, entry_type);
        let decoded = decode_internal_key_typed(&encoded);

        // Assert - roundtrip should preserve data
        let (dec_key, dec_seq, dec_type) = decoded.expect("valid encoding should decode");
        prop_assert_eq!(dec_key, user_key);
        prop_assert_eq!(dec_seq, seq);
        prop_assert_eq!(dec_type, entry_type);
    }
}

// ============================================================================
// Edge Case Tests
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1_000))]

    #[test]
    fn should_handle_boundary_sizes_when_parsing_tlv(size in 0usize..128) {
        // Arrange - generate data of specific size
        let data: Vec<u8> = (0..size).map(|i| i as u8).collect();

        // Act
        let reader = TlvReader::new(&data);
        for _ in reader {}
        let _ = decode_varint32(&data);
        let _ = decode_varint64(&data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_handle_all_byte_values_when_parsing_single_byte(byte in any::<u8>()) {
        // Arrange - test every possible byte value
        let data = [byte];

        // Act - all parsers should handle single bytes
        let reader = TlvReader::new(&data);
        for _ in reader {}
        let _ = decode_varint32(&data);
        let _ = decode(&data);
        let _ = Block::decode(&data, BlockType::Data);

        // Assert - implicit (no panic)
    }

    #[test]
    fn should_handle_repeated_patterns_when_parsing(
        pattern in prop::collection::vec(any::<u8>(), 1..8),
        repeat in 1usize..100
    ) {
        // Arrange - create repeated pattern
        let data: Vec<u8> = pattern.iter().cycle().take(pattern.len() * repeat).copied().collect();

        // Act
        let reader = TlvReader::new(&data);
        for _ in reader {}
        let _ = decode(&data);
        let _ = SparseIndex::decode(&data);

        // Assert - implicit (no panic)
    }
}

// ============================================================================
// Specific Pattern Tests (regression-style)
// ============================================================================

#[test]
fn should_handle_empty_input_when_parsing_all_formats() {
    // Arrange
    let empty: &[u8] = &[];

    // Act
    let reader = TlvReader::new(empty);
    let count = reader.count();
    let varint32_result = decode_varint32(empty);
    let varint64_result = decode_varint64(empty);
    let wal_result = decode(empty);
    let wal_borrowed_result = decode_borrowed(empty);
    let block_result = Block::decode(empty, BlockType::Data);
    let sparse_result = SparseIndex::decode(empty);

    // Assert
    assert_eq!(count, 0);
    assert!(varint32_result.is_err());
    assert!(varint64_result.is_err());
    assert!(wal_result.is_err());
    assert!(wal_borrowed_result.is_err());
    assert!(block_result.is_err());
    assert!(sparse_result.is_ok()); // Empty index is valid
}

#[test]
fn should_handle_max_values_when_decoding_varints() {
    // Arrange - maximum varint32 encoding (5 bytes)
    let max_u32_bytes = [0xFF, 0xFF, 0xFF, 0xFF, 0x0F];
    // Maximum varint64 encoding (10 bytes)
    let max_u64_bytes = [0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x01];

    // Act
    let (val32, len32) = decode_varint32(&max_u32_bytes).expect("valid max u32");
    let (val64, len64) = decode_varint64(&max_u64_bytes).expect("valid max u64");

    // Assert
    assert_eq!(val32, u32::MAX);
    assert_eq!(len32, 5);
    assert_eq!(val64, u64::MAX);
    assert_eq!(len64, 10);
}

#[test]
fn should_reject_overlong_varints() {
    // Arrange - 6-byte varint32 (overflow)
    let overlong = [0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x01];

    // Act
    let result = decode_varint32(&overlong);

    // Assert - should error, not wrap or panic
    assert!(result.is_err());
}
