name: Bench

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: rust-bench-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Bench
        run: cargo bench
